import './sass/main.scss';
import './js/header';
import './js/gallery';
import './js/footer';
import './js/pagination';
import './js/modal';
import './js/reference';
import './js/scrollToTop';
import './js/service/api';
